/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cats_project;

import javax.swing.JOptionPane;

/**
 *
 * @author Aditya Rathi
 */
public class MachinePanel extends javax.swing.JPanel {

    private ServerSidePanelFrame mainFrame;
    private int index = -1;
    /**
     * Creates new form MachinePanel
     */
    public MachinePanel(ServerSidePanelFrame mainFrame, int index) {
        this.mainFrame = mainFrame;
        this.index = index;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configureButton = new javax.swing.JButton();
        jMachineName = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        configureButton.setText("Configure");
        configureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configureButtonActionPerformed(evt);
            }
        });

        jMachineName.setText("Machine");

        removeButton.setText("Remove");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jMachineName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(removeButton)
                .addGap(18, 18, 18)
                .addComponent(configureButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(configureButton)
                    .addComponent(jMachineName)
                    .addComponent(removeButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configureButtonActionPerformed
        // TODO add your handling code here:
        String machineName = JOptionPane.showInputDialog("Enter Machine Name: ",mainFrame.machineObjectsList.get(index).getMachineName());
        String machineAddress = JOptionPane.showInputDialog("Enter Address for "+machineName+" : ",mainFrame.machineObjectsList.get(index).getMachineAddress());
        mainFrame.machineObjectsList.get(index).setMachineName(machineName);
        mainFrame.machineObjectsList.get(index).setMachineAddress(machineAddress);
        
    }//GEN-LAST:event_configureButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:
        mainFrame.machineObjectsList.remove(index);
        mainFrame.refreshMachineView();
        
    }//GEN-LAST:event_removeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configureButton;
    private javax.swing.JLabel jMachineName;
    private javax.swing.JButton removeButton;
    // End of variables declaration//GEN-END:variables
}
